char turn_rightmost_1bit_off(char x);
char turn_rightmost_0bit_on(char x);
char turn_trailing_1s_off(char x);
char turn_trailing_0s_on(char x);
char take_single_rightmost_0(char x);
char all_1s_except_rightmost_1(char x);
unsigned snoob(unsigned x);
unsigned xor(unsigned a, unsigned b);
unsigned bitwise_and(unsigned a, unsigned b);
unsigned bitwise_or(unsigned a, unsigned b);
int abs(int x);
int sign(int x);
unsigned avg_floor(unsigned a, unsigned b);
unsigned avg_ceil(unsigned a, unsigned b);
int equal_to_zero(int x);
int not_equal_to_zero(int x);
int less_than_zero(int x);
int less_than_or_equal_to_zero(int x);
int greater_than_zero(int x);
int greater_than_or_equal_to_zero(int x);
int sum_overflows(int x, int y, int c);
int division_overflows(int x, int y);
int count_bits(int x);
void swap(int *x, int *y);
int branch(int a, int b, int cond);
int is_odd(int x);
int is_even(int x);
int same_sign(int x, int y);
int rotate_left(int x, int n);
int rotate_right(int x, int n);
